# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json package-lock.json .
RUN npm install --ignore-scripts

# Copy source code
COPY . .

# Build the project
RUN npm run build

# Ensure the binary is executable
RUN chmod +x build/ai.js

# Use unprivileged user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

# Default command: run MCP over stdio
CMD ["node", "build/ai.js"]
